### ISSUE TITLE
Test PUNCH IDL tools on Windows

### ISSUE THREAD

**Issue by jmbhughes** [punch-mission/PUNCH_IDL_Tools#11]
Make sure PUNCH reader works. If it has problems, open a follow up issue to resolve the problem. 

*work log*:
- @s0larish : ? hours

**Comment by jmbhughes** [comment]
![Image](https://github.com/punch-mission/PUNCH_IDL_Tools/assets/13068381/89dde8bd-9533-4b78-9b7c-97be800642e6)

Ritesh tested and notes, "Tested the updated routines on Windows machine. Though it worked for EUI data, but encountered error for synthetic PUNCH data I used for testing (L3 NFI and L2 QuickPUNCH)."

**Comment by jmbhughes** [comment]
@s0larish do you know what is making it fail on our files?

**Comment by s0larish** [comment]
The first difference I can see between the two data is we have multiple compressed HDUs while EUI has only one compressed one. I will let the IDL team know this issue if they can further update their routines.

**Comment by jmbhughes** [comment]
@s0larish please note how many hours you spent on this. Since this issue was just to *test* we should open another to *fix*.

**Comment by s0larish** [comment]
We can keep 1 hour for testing.
