### ISSUE TITLE
Fix IDL tools so it loads PUNCH data on Windows

### ISSUE THREAD

**Issue by jmbhughes** [punch-mission/PUNCH_IDL_Tools#12]
Tasks
- [x] identify the problem that's preventing it
- [ ] work with others to implement a solution
- [ ] test solution
- [ ] document any changes users need to make so it works
- [ ] release

*work log*:
- @s0larish : 2.5 hours

**Comment by lowderchris** [comment]
Here are two sample files with minimal header information. A 3x512x512 array and a 512x512 array, each filled with randomly distributed data. Each was assembled into a CompImageHDU structure (just the data passed in), bundled with an empty PrimaryHDU, and written to file.

[compfits_test_data.zip](https://github.com/punch-mission/PUNCH_IDL_Tools/files/13641294/compfits_test_data.zip)

**Comment by s0larish** [comment]
The two random data files were successfully read on Windows machine :)

(attached screenshots for the two)


![Screenshot (103)](https://github.com/punch-mission/PUNCH_IDL_Tools/assets/84658086/f3d59706-30bb-4c0d-9504-cd8bfb3d520b)
![Screenshot (102)](https://github.com/punch-mission/PUNCH_IDL_Tools/assets/84658086/a7a077ba-9208-488f-af88-96a8f3656a1d)

**Comment by lowderchris** [comment]
Does IDL properly read that one file as a datacube? I don't know what read_sdo assumes about the data shape.

**Comment by s0larish** [comment]
IDL routines do have options to provide extension number to read. I will explore today afternoon for the ones I used here.

**Comment by s0larish** [comment]
Though it is able to read these fits files but unable to generate the data cube that is anticipated. The one I mentioned for reading the extension number is available for decompressed files only.

**Comment by jmbhughes** [comment]
Our version is working. We will reopen if needed.
